### PR TITLE
feat: add structured query

### LINKED ISSUE #14: Convert query results into line protocol
### Use Case

Users who want to query data from InfluxDB Cloud, transform it, and then write it back into InfluxDB. For example users who want to perform downsampling need a way to query the data, downsample it, convert it back into line protocol, and then write it. 

### Expected behavior

Convert the query results into line protocol. 

### Actual behavior

Feature request, doesn't exist yet. Thank you! 

### Additional info

_No response_

### LINKED ISSUE #43: Type-safe conversion for line-protocol Addfield
### Use Case

- I want asserure that AddField() without panicking.
- avoiding reflect.
- Please show me the error while I am editing in VSCode.

### Expected behavior

- use unsupported types, then compile error.

```go
func example() {
	p := NewPoint("measurement", map[string]string{}, map[string]interface{}{"measurement": "air"}, time.Now())
        // unsupported type.
	p.AddFieldFromValue("✅ Compile error.", cmplx.Inf())
        // supported type.
	p.AddFieldFromValue("✅ This is safe.", NewValueFromInt(255))
}

```
### Actual behavior

- use unsupported types, then panic.

```go
func example() {
	p := NewPoint("measurement", map[string]string{}, map[string]interface{}{"measurement": "air"}, time.Now())
        // unsupported type.
	p.AddField("❌ Will panic.", cmplx.Inf())
        // supported type.
	p.AddField("❓This is OK, but really?", 255)
}

```

### Additional info

- #42
- Which API do you prefer(NewValueFrom VS NewFieldFrom)?
  - NewValueFrom  wins.

#### NewValueFrom 

```go
func (m *Point) AddFieldFromValue(k string, v lineprotocol.Value) *Point {}
func NewValueFromInt[I Integer](v I) lineprotocol.Value {}
```

#### (Retracted)NewFieldFrom

```go
func (m *Point) AddFieldRaw(k string, v Field) *Point {}
func NewFieldFromInt[I Integer](v I) Field {}
```

### Why not line-protocol?

- line-protocol v2 [dont support generics yet](https://github.com/influxdata/line-protocol/blob/v2/go.mod).

### LINKED ISSUE #44: Simple Addvalue types
### Use Case

- When the type is explanatory, allow simple addition
  - see https://github.com/InfluxCommunity/influxdb3-go/pull/42#issuecomment-1744561920

### Expected behavior

I can easily add strings, integers, and floats. example

```go
func (m *Point) AddStringField(k string, v string) *Point {
	m.AddField(k, v)
	return m
}

```
### Actual behavior

It is not here.

### Additional info

  - relates #43

### PR DESCRIPTION
**Pull request by bednar**
Closes #14 
Closes #43 
Closes #44

## Proposed Changes

The user is able to query data into structured object and write this object back to database.

## Checklist

- [x] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] A test has been added if appropriate
- [x] Tests pass
- [x] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

### CODE REVIEW

**Comment by arukiidou** [comment]
please add `SetUIntegerField`.

**Review by Sciator — APPROVED** [review]

**Comment by nrhvyc** [comment]
Why use Setter functions here instead of following the convention used by `func (c *Client) WriteData{}` which uses field tags? It's not like Values is a private field that would require a setter. Doesn't feel like idiomatic Go code.

> type TemperatureSensor struct {
	Measurement  string    `lp:"measurement"`
	Sensor       string    `lp:"tag,sensor"`
	ID           string    `lp:"tag,device_id"`
	Temp         float64   `lp:"field,temperature"`
	Hum          int       `lp:"field,humidity"`
	Time         time.Time `lp:"timestamp"`
	Description  string    `lp:"-"`
}

**Comment by bednar** [comment]
Hi @nrhvyc,

Thank you for your input. Could you please provide more details about your suggestion? I'm not sure I've fully understood what you are proposing. Any additional information you can provide would be helpful.

Best regards

**Comment by bednar** [comment]
@arukiidou 

> please add `SetUIntegerField`.

I will update this PR

**Comment by bednar** [comment]
@nrhvyc, please feel free to suggest improvements to the client. We are always happy to consider changes that will enhance usability for our community. Our minds are open. ;)

**Pull request merged**
