### PR TITLE
fix: unclosed body causing resource leak

### PR DESCRIPTION
**Pull request by jdockerty**
## Proposed Changes

When the returned `Response`'s body is `nil`, the caller of the function is expected to `Close` the body. If this is not done, it can lead to a resource leak.

[Ref](https://pkg.go.dev/net/http#Client.Do)

>If the returned error is nil, the Response will contain a non-nil Body which the user is expected to close.

This is also caught by a `golangci-lint` check of `bodyclose`, e.g. running from `main`:

```bash
git branch --show-current
main

golangci-lint run --enable-only bodyclose
influxdb3/management_cloud_decicated.go:146:31: response body must be closed (bodyclose)
        _, err = d.client.makeAPICall(ctx, param)
                                     ^
influxdb3/management_serverless.go:98:31: response body must be closed (bodyclose)
        _, err = c.client.makeAPICall(ctx, param)
                                     ^
influxdb3/write.go:168:24: response body must be closed (bodyclose)
        _, err = c.makeAPICall(ctx, httpParams{
                              ^
```

Other references:

- [What if I don't close the response body?](https://stackoverflow.com/questions/33238518/what-could-happen-if-i-dont-close-response-body)
- [Go Response Body MUST be closed, even if you don't read it](https://manishrjain.com/must-close-golang-http-response)

This is mainly believed to effect a Clustered customer, but I've also addressed the lint elsewhere too for Cloud Dedicated/Serverless[^1].

[^1]: This also shows up in various tests, but I've opted to leave this for now because they are ephemeral compared to client usage. If needs be I think someone can address these in a follow-up PR.

## Checklist

- [x] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] A test has been added if appropriate
- [x] Tests pass
- [ ] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

### CODE REVIEW

**Comment by jdockerty** [comment]
I don't believe this has any behavioural change, i.e. the `err` is still returned when it occurs and `resp.Body.Close` also returns an `error` which upholds the return value for `Client.write`. I'm not quite convinced the code coverage complaint here is giving us much.

Happy to take suggestions on what to do for proceeding here though :+1:

**Review by bednar — CHANGES_REQUESTED** [review]
Thanks for your PR 👍 

The failing code coverage check is due to our CI settings. Forked repositories do not run integration tests against InfluxDB Cloud to keep credentials secure. This will be addressed once InfluxDB Edge OSS is released.

Could you please update the `CHANGELOG.md`? After that, we'll be able to merge your awesome PR!

**Review by bednar — APPROVED** [review]
LGTM 🚀 

I've prepared the integration of `golangci-lint` into our CI pipeline with PR #95. I'll merge this PR after we finalize #95.

**Review by bednar — CHANGES_REQUESTED** [review]
The #95 is merged. 

Please rebase your PR and add `bodyclose` to: https://github.com/InfluxCommunity/influxdb3-go/blob/5b9dc92fb66056c17fb7c5a18ce9ba2a42bd8ab2/.golangci.yml#L4-L9

**Comment by jdockerty** [comment]
@bednar Sure thing :+1: 

>  add `bodyclose`

As a small heads up for this. I raised this in the PR description, but this `bodyclose` lint is actually prevelent throughout the codebase, e.g. in many tests. If I add the `bodyclose` lint here, then it will fail until _all_ instances of it are fixed.

Do we want to add those to this PR in that case or save the `bodyclose` CI addition for another PR?

**Comment by bednar** [comment]
> **Edit:** It looks like I can add `--tests=false` to `golangci-lint` to solve that, if we're okay with it?

Yes, it is good approach. Thanks @jdockerty

**Comment by jdockerty** [comment]
So I believe this is a bit of double-edged sword unfortunately.

Using `--tests=false` means that the `*_test.go` files are not being analyzed, which means all of the `bodyclose` lints do not need to be addressed here; however, I believe that then has a knock-on effect such that it causes different lints to fail. 

For example, by disabling the analysis of tests, it _looks_ like the `setQueryClient` is unused:

```bash
golangci-lint run -v --tests=false --config .golangci.yml
...snip
influxdb3/query.go:70:18  unused  func `(*Client).setQueryClient` is unused
1 issues:
* unused: 1
```

In actual fact this isn't the case though, it _is_ used, but within tests :smile: 

```
rg "setQueryClient"
influxdb3/query_test.go
100:    c.setQueryClient(fc)
145:    c.setQueryClient(fc)

influxdb3/query.go
70:func (c *Client) setQueryClient(flightClient flight.Client) {
```

@bednar Any preference on how to proceed with this? I can either:

- Address _all_ `bodyclose` lints in this PR
- Don't introduce the `bodyclose` lint yet (not ideal as it is quite useful)
- Any other ideas?

**Review by bednar — APPROVED** [review]
@jdockerty, thank you for your efforts ❤️ 

I've disabled `bodyclose` from the CI checks, and we can consider re-enabling it in a subsequent PR or during the enhancement of the golangci-lint configuration as described here: [Enhance golangci-lint Configuration](https://github.com/orgs/influxdata/projects/108/views/1?pane=issue&itemId=74621090).

**Pull request merged**
